spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:mysql://databaseurl:3306/courses_no_one_asked_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

security.jwt.secret=supersecretkeyforjwtsigning
