apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: cnoaf
spec:
  replicas: 1

  selector:
    matchLabels:
      app: course-service

  template:
    metadata:
      labels:
        app: course-service

    spec:
      containers:
        - name: course-service
          image: <account-id>.dkr.ecr.<region>.amazonaws.com/cnoaf/course-service:latest

          ports:
            - containerPort: 8082
